import { Database, Sparkles, CheckCircle2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

interface LocalSourceBadgeProps {
  fromLearning?: boolean;
  fromDatabase?: boolean;
  language?: string;
  className?: string;
}

export function LocalSourceBadge({ 
  fromLearning, 
  fromDatabase, 
  language = 'fr',
  className 
}: LocalSourceBadgeProps) {
  // If the result comes from the local learning database
  if (fromLearning) {
    return (
      <div className={cn(
        "flex items-center gap-2 p-3 rounded-xl bg-gradient-to-r from-purple-500/10 via-purple-500/5 to-blue-500/10 border border-purple-500/20",
        className
      )}>
        <div className="w-10 h-10 rounded-full bg-purple-500/20 flex items-center justify-center shrink-0">
          <Database className="w-5 h-5 text-purple-600" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-0.5">
            <span className="text-sm font-semibold text-purple-600">
              {language === 'fr' ? 'Diagnostic local' : 'Local diagnosis'}
            </span>
            <Badge variant="outline" className="bg-purple-500/10 text-purple-600 border-purple-500/30 text-xs">
              <CheckCircle2 className="w-3 h-3 mr-1" />
              {language === 'fr' ? 'Apprentissage IA' : 'AI Learning'}
            </Badge>
          </div>
          <p className="text-xs text-muted-foreground">
            {language === 'fr' 
              ? 'Ce diagnostic provient de notre base de données locale, enrichie par les diagnostics précédents dans votre région.'
              : 'This diagnosis comes from our local database, enriched by previous diagnoses in your region.'
            }
          </p>
        </div>
      </div>
    );
  }

  // If the result comes from the main database
  if (fromDatabase) {
    return (
      <div className={cn(
        "flex items-center gap-2 p-3 rounded-xl bg-gradient-to-r from-blue-500/10 via-blue-500/5 to-cyan-500/10 border border-blue-500/20",
        className
      )}>
        <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center shrink-0">
          <Database className="w-5 h-5 text-blue-600" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-0.5">
            <span className="text-sm font-semibold text-blue-600">
              {language === 'fr' ? 'Base de données' : 'Database'}
            </span>
            <Badge variant="outline" className="bg-blue-500/10 text-blue-600 border-blue-500/30 text-xs">
              <CheckCircle2 className="w-3 h-3 mr-1" />
              {language === 'fr' ? 'Référentiel expert' : 'Expert reference'}
            </Badge>
          </div>
          <p className="text-xs text-muted-foreground">
            {language === 'fr' 
              ? 'Ce diagnostic provient de notre base de données agricole camerounaise validée par des experts.'
              : 'This diagnosis comes from our Cameroonian agricultural database validated by experts.'
            }
          </p>
        </div>
      </div>
    );
  }

  // If the result comes from pure AI analysis
  return (
    <div className={cn(
      "flex items-center gap-2 p-3 rounded-xl bg-gradient-to-r from-primary/10 via-primary/5 to-accent/10 border border-primary/20",
      className
    )}>
      <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center shrink-0">
        <Sparkles className="w-5 h-5 text-primary" />
      </div>
      <div className="flex-1">
        <div className="flex items-center gap-2 mb-0.5">
          <span className="text-sm font-semibold text-primary">
            {language === 'fr' ? 'Analyse IA' : 'AI Analysis'}
          </span>
          <Badge variant="outline" className="bg-primary/10 text-primary border-primary/30 text-xs">
            <Sparkles className="w-3 h-3 mr-1" />
            {language === 'fr' ? 'Nouveau diagnostic' : 'New diagnosis'}
          </Badge>
        </div>
        <p className="text-xs text-muted-foreground">
          {language === 'fr' 
            ? 'Ce diagnostic a été généré par notre IA. Il sera ajouté à la base d\'apprentissage locale.'
            : 'This diagnosis was generated by our AI. It will be added to the local learning database.'
          }
        </p>
      </div>
    </div>
  );
}
